=== doubleunion/opendiversitydata/schema/eeo-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "opendiversitydata",
  "version": "0.0.2",
  "description": "JSON schema for U.S. EEO-1 survey data",
  "type": "object",
  "properties": {
    "meta": {
      "type": "object",
      "properties": { 
        "company": {
          "type": "string"
        },
        "year": {
          "type": "integer",
          "minimum": 1965,
          "maximum": 2014
        }
      },
      "required": ["company", "year"]
    },
    "section_a": {
      "type": "object",
      "properties": {
        "reporting_type": {
          "type": "string",
          "enum": [
            "Single-establishement Employer Report",
            "Consolidated Report",
            "Headquarters Unit Report",
            "Individual Establishment Report",
            "Special Report"
          ]
        }
      },
      "required": ["reporting_type"]
    },
    "section_b": {
      "type": "object",
      "properties": {
        "parent_company": {
          "type": "string"
        },
        "address": {
          "type": "object",
          "properties": {
            "street_address": { "type": "string" },
            "city": { "type": "string" },
            "state": {
              "type": "string",
              "enum": ["AL", "AK", "AS", "AZ", "AR", "CA", "CO", "CT", "DE", "DC", "FM", "FL", "GA", "GU", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", "ME", "MH", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "MP", "OH", "OK", "OR", "PW", "PA", "PR", "RI", "SC", "SD", "TN", "TX", "UT", "VT", "VI", "VA", "WA", "WV", "WI", "WY"]
            },
            "zip_code": { "type": "string" }
          },
          "required": ["street_address", "city", "state", "zip_code"]
        },
        "previous_year_report": {
          "type": "boolean"
        }
      },
      "required": ["parent_company", "address", "previous_year_report"]
    },
    "section_c": {
      "type": "object",
      "properties": {
        "at_least_100": { "type": "boolean" },
        "affiliated": { "type": "boolean" },
        "DUNS": { "type": "boolean" }
      },
      "required": ["at_least_100", "affiliated", "DUNS"]
    },
    "section_d": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "job_category": {
            "type": "string",
            "enum": [
              "Executive/Senior Level Officials and Managers",
              "First/Mid Level Officials and Managers",
              "Professionals",
              "Technicians",
              "Sales Workers",
              "Administrative Support Workers",
              "Craft Workers",
              "Operatives",
              "Laborers and Helpers",
              "Service Workers"
            ]
          },
          "data": {
            "type": "array",
            "items": {
              "properties": {
                "race": {
                  "type": "string",
                  "enum": [
                    "Hispanic or Latino",
                    "White",
                    "Black or African American",
                    "Native Hawaiian or Other Pacific Islander",
                    "Asian",
                    "American Indian or Alaska Native",
                    "Two or More Races"
                  ]
                },
                "men": {
                  "type": "integer",
                  "minimum": 0
                },
                "women": {
                  "type": "integer",
                  "minimum": 0
                }
              },
              "required": ["race", "men", "women"]
            },
            "minItems": 7,
            "maxItems": 7,
            "uniqueItems": true
          }
        },
        "required": ["job_category", "data"]
      },
      "minItems": 10,
      "maxItems": 10,
      "uniqueItems": true
    }
  },
  "required": ["meta", "section_d"]
}

=== doubleunion/opendiversitydata/json/dell.json
{
  "meta": {
    "company": "Dell",
    "year": 2010
  },
  "section_a": { "reporting_type": "Consolidated Report" },
  "section_b": {
    "parent_company": "DELL INC - (DELL USA) - ROUND ROCK",
    "address": {
      "street_address": "401 DELL WAY",
      "city": "ROUND ROCK",
      "state": "TX",
      "zip_code": "78682"
    },
    "previous_year_report": true
  },
  "section_c": {
    "at_least_100": true,
    "affiliated": false,
    "DUNS": true
  },
  "section_d": [
    {
      "job_category": "Executive/Senior Level Officials and Managers",
      "data": [
        {
          "race": "Hispanic or Latino",
          "men": 0,
          "women": 0
        },
        {
          "race": "White",
          "men": 98,
          "women": 28
        },
        {
          "race": "Black or African American",
          "men": 1,
          "women": 0
        },
        {
          "race": "Native Hawaiian or Other Pacific Islander",
          "men": 0,
          "women": 0
        },
        {
          "race": "Asian",
          "men": 8,
          "women": 2
        },
        {
          "race": "American Indian or Alaska Native",
          "men": 0,
          "women": 0
        },
        {
          "race": "Two or More Races",
          "men": 0,
          "women": 0
        }
      ]
    },
    {
      "job_category": "First/Mid Level Officials and Managers",
      "data": [
        {
          "race": "Hispanic or Latino",
          "men": 170,
          "women": 90
        },
        {
          "race": "White",
          "men": 2604,
          "women": 975
        },
        {
          "race": "Black or African American",
          "men": 132,
          "women": 78
        },
        {
          "race": "Native Hawaiian or Other Pacific Islander",
          "men": 1,
          "women": 1
        },
        {
          "race": "Asian",
          "men": 244,
          "women": 78
        },
        {
          "race": "American Indian or Alaska Native",
          "men": 8,
          "women": 6
        },
        {
          "race": "Two or More Races",
          "men": 16,
          "women": 3
        }
      ]
    },
    {
      "job_category": "Professionals",
      "data": [
        {
          "race": "Hispanic or Latino",
          "men": 904,
          "women": 482
        },
        {
          "race": "White",
          "men": 8164,
          "women": 3562
        },
        {
          "race": "Black or African American",
          "men": 683,
          "women": 434
        },
        {
          "race": "Native Hawaiian or Other Pacific Islander",
          "men": 17,
          "women": 7
        },
        {
          "race": "Asian",
          "men": 1884,
          "women": 780
        },
        {
          "race": "American Indian or Alaska Native",
          "men": 51,
          "women": 19
        },
        {
          "race": "Two or More Races",
          "men": 98,
          "women": 41
        }
      ]
    },
    {
      "job_category": "Technicians",
      "data": [
        {
          "race": "Hispanic or Latino",
          "men": 311,
          "women": 57
        },
        {
          "race": "White",
          "men": 2186,
          "women": 303
        },
        {
          "race": "Black or African American",
          "men": 341,
          "women": 104
        },
        {
          "race": "Native Hawaiian or Other Pacific Islander",
          "men": 7,
          "women": 0
        },
        {
          "race": "Asian",
          "men": 201,
          "women": 29
        },
        {
          "race": "American Indian or Alaska Native",
          "men": 33,
          "women": 10
        },
        {
          "race": "Two or More Races",
          "men": 49,
          "women": 7
        }
      ]
    },
    {
      "job_category": "Sales Workers",
      "data": [
        {
          "race": "Hispanic or Latino",
          "men": 287,
          "women": 80
        },
        {
          "race": "White",
          "men": 3318,
          "women": 964
        },
        {
          "race": "Black or African American",
          "men": 226,
          "women": 71
        },
        {
          "race": "Native Hawaiian or Other Pacific Islander",
          "men": 6,
          "women": 1
        },
        {
          "race": "Asian",
          "men": 145,
          "women": 39
        },
        {
          "race": "American Indian or Alaska Native",
          "men": 24,
          "women": 9
        },
        {
          "race": "Two or More Races",
          "men": 47,
          "women": 17
        }
      ]
    },
    {
      "job_category": "Administrative Support Workers",
      "data": [
        {
          "race": "Hispanic or Latino",
          "men": 232,
          "women": 470
        },
        {
          "race": "White",
          "men": 720,
          "women": 2203 
        },
        {
          "race": "Black or African American",
          "men": 192,
          "women": 609
        },
        {
          "race": "Native Hawaiian or Other Pacific Islander",
          "men": 2,
          "women": 17
        },
        {
          "race": "Asian",
          "men": 81,
          "women": 180
        },
        {
          "race": "American Indian or Alaska Native",
          "men": 11,
          "women": 36
        },
        {
          "race": "Two or More Races",
          "men": 9,
          "women": 31
        }
      ]
    },
    {
      "job_category": "Craft Workers",
      "data": [
        {
          "race": "Hispanic or Latino",
          "men": 1,
          "women": 0
        },
        {
          "race": "White",
          "men": 0,
          "women": 0
        },
        {
          "race": "Black or African American",
          "men": 0,
          "women": 1
        },
        {
          "race": "Native Hawaiian or Other Pacific Islander",
          "men": 0,
          "women": 0
        },
        {
          "race": "Asian",
          "men": 0,
          "women": 0
        },
        {
          "race": "American Indian or Alaska Native",
          "men": 0,
          "women": 0
        },
        {
          "race": "Two or More Races",
          "men": 0,
          "women": 0
        }
      ]
    },
    {
      "job_category": "Operatives",
      "data": [
        {
          "race": "Hispanic or Latino",
          "men": 75,
          "women": 40
        },
        {
          "race": "White",
          "men": 104,
          "women": 67
        },
        {
          "race": "Black or African American",
          "men": 79,
          "women": 88
        },
        {
          "race": "Native Hawaiian or Other Pacific Islander",
          "men": 0,
          "women": 0
        },
        {
          "race": "Asian",
          "men": 28,
          "women": 15
        },
        {
          "race": "American Indian or Alaska Native",
          "men": 1,
          "women": 0
        },
        {
          "race": "Two or More Races",
          "men": 0,
          "women": 0
        }
      ]
    },
    {
      "job_category": "Laborers and Helpers",
      "data": [
        {
          "race": "Hispanic or Latino",
          "men": 0,
          "women": 0
        },
        {
          "race": "White",
          "men": 0,
          "women": 0
        },
        {
          "race": "Black or African American",
          "men": 0,
          "women": 0
        },
        {
          "race": "Native Hawaiian or Other Pacific Islander",
          "men": 0,
          "women": 0
        },
        {
          "race": "Asian",
          "men": 0,
          "women": 0
        },
        {
          "race": "American Indian or Alaska Native",
          "men": 0,
          "women": 0
        },
        {
          "race": "Two or More Races",
          "men": 0,
          "women": 0
        }
      ]
    },
    {
      "job_category": "Service Workers",
      "data": [
        {
          "race": "Hispanic or Latino",
          "men": 6,
          "women": 9
        },
        {
          "race": "White",
          "men": 45,
          "women": 65
        },
        {
          "race": "Black or African American",
          "men": 7,
          "women": 15
        },
        {
          "race": "Native Hawaiian or Other Pacific Islander",
          "men": 0,
          "women": 0
        },
        {
          "race": "Asian",
          "men": 2,
          "women": 1
        },
        {
          "race": "American Indian or Alaska Native",
          "men": 0,
          "women": 0
        },
        {
          "race": "Two or More Races",
          "men": 1,
          "women": 0
        }
      ]
    }
  ]
}
